### ISSUE TITLE
golangci_lint ignores pkg/server

### ISSUE THREAD

**Issue by klavinsjanis** [translate-agent/translate#171]
Missed this when refactored pkg names. As a result, all handlers were not linted

```yaml
run:
  build-tags:
    - integration
  timeout: 2m
  skip-dirs:
    - pkg/server # <---- change to pkg/pb
```
